#!/bin/bash
ROOT=$(dirname $0)
N=${1:-16}; shift
LIMIT=${1:-30}; shift

echo "$(basename $0): $N/$LIMIT"
seq 1 $N | xargs -n1 -I@ -P$N \
	$ROOT/alertspam timed $LIMIT $ROOT/../send_iris -q -H 127.0.0.1 -p 5668
